### ISSUE TITLE
rubygems version is broken

### ISSUE THREAD

**Issue by Signum** [joaopapereira/omniauth-launchpad#1]
The rubygems version has this line in /lib/omniauth/strategies/launchpad.rb (#27):

You fixed that in commit https://github.com/joaopapereira/omniauth-launchpad/commit/3a29e5a89bf52e70d20b8f461a9c9bf8f5d6dab8 but missed to re-upload to rubygems.

Could you do that please?

**Comment by joaopapereira** [comment]
Hello,
I pushed a version 0.1.0 hope that it fixes your problem.
If there is any other issue just open a issue :D
